name = "pb"
compatibility_date = "2023-01-28"

workers_dev = false
main = "src/index.js"

rules = [
  { type = "Text", globs = [ "*.html", "*.client.js", "*.md", "*.css" ], fallthrough = true }
]

#----------------------------------------
# lines below are what you should modify
#----------------------------------------

[[routes]]
# Refer to https://developers.cloudflare.com/workers/wrangler/configuration/#routes
pattern = "pb.wzme.net"
custom_domain = true

[[kv_namespaces]]
binding = "PB"  # do not touch this
id = "fc9d70d065fd492ab76a78b4f972ae11"  # id of your KV namespace

[vars]
# must be consistent with your routes
BASE_URL = "https://pb.wzme.net"

# url to repo, displayed in index page
REPO = "https://github.com/integer2bit/pastebin-worker"

# url to favicon
FAVICON = "https://file.wzme.net/image/pastebin-svgrepo-com.svg"

# the name displayed in TOS
TOS_MAINTAINER = "integer2bit"

# the email displayed in TOS
TOS_MAIL = "pb@wzme.net"

# Cache-Control max-age for static pages
CACHE_STATIC_PAGE_AGE = 7200

# Cache-Control max-age for static pages
CACHE_PASTE_AGE = 600
